services:
  sms-gate:
    env_file:
      - .env
    build:
      context: ./sms-gate
      dockerfile: ./Dockerfile
    networks:
      - common

  bank:
    env_file:
      - .env
    build:
      context: ./bank
      dockerfile: ./Dockerfile
    networks:
      - common
    dns:
      - 1.1.1.1
      - 8.8.8.8
    dns_search: []

networks:
  common:
    driver: bridge

