services:
  sms-gate:
    env_file:
      - .env
    build:
      context: ./sms-gate
      dockerfile: ./Dockerfile
    networks:
      - common

  bank:
    env_file:
      - .env
    build:
      context: ./bank
      dockerfile: ./Dockerfile
    networks:
      - common

networks:
  common:
    driver: bridge

